version: "3.9"

services:
  ragagent:
    build:
      context: .
      dockerfile: Agent/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://ragagent:8000/search
    depends_on:
      - ragagent