apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: us-central1-docker.pkg.dev/gket10-aistyleagent/gket10/agent:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: agent-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: agent
spec:
  selector:
    app: agent
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP